apiVersion: v1
data:
  channel-template-spec: |
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 10
      replicationFactor: 3
kind: ConfigMap
metadata:
  name: config-br-default-channel
  namespace: knative-eventing
