apiVersion: v1
data:
  default-br-config: |
    clusterDefault:
      brokerClass: Kafka
      apiVersion: v1
      kind: ConfigMap
      name: kafka-broker-config
      namespace: knative-eventing
    namespacedefaults:
      some-namespace:
        brokerClass: MTChannelBasedBroker
        apiVersion: v1
        kind: ConfigMap
        name: config-br-default-channel
        namespace: knative-eventing
        delivery:
          retry: 10
          backoffPolicy: exponential
          backoffDelay: PT0.2S
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
