apiVersion: v1
kind: Secret
metadata:
  name: gitlabsecret
  namespace: event-demo
type: Opaque
stringData:
  accessToken: glpat-K1HzkExzXyye-gnhkMyg   # 这是 gitlab 下生成的个人私有访问令牌
  secretToken: mrwuxlyw0+hZTLTmpEWIpA       # openssl rand -hex 8 随机生成,验证 gitlab 发来的消息，gitlab 上也要配置
