---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka
  namespace: knative-eventing
data:
  eventing-kafka: |
    kafka:
      brokers: my-cluster-kafka-bootstrap.kafka:9092
  version: 1.0.0